### ISSUE TITLE
Conversation with contact not using OTR

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#18]
When starting a conversation with a contact who is not using OTR, the message is:

2:41:23 pm - The current conversation is not private.
2:41:26 pm - You attempted to send an unencrypted message to sukhe. Unencrypted messages to this recipient are not allowed. Attempting to start a private conversation. Your message will be retransmitted when the private conversation starts.

I think we can word this better. Specifically, saying "Unencrypted messages to this recipient are not allowed" makes it seem like that this specific contact is the issue and not the fact that unencrypted conversations are not allowed as a policy.

A possible suggestion:

You attempted to send an unencrypted message to sukhe. This contact does not support encrypted communication and Tor Messenger does not allow unencrypted messages to be sent. 

And then, in a separate message which follows (on a new line):

Attempting to start a private conversation. Your message will be retransmitted when the private conversation starts.

Something along these lines...

**Comment by arlolra** [comment]
> Specifically, saying "Unencrypted messages to this recipient are not allowed" makes it seem like that this specific contact is the issue and not the fact that unencrypted conversations are not allowed as a policy.

Good point. I changed it to,

11:02:34 AM - You attempted to send an unencrypted message to testuser. As a policy, unencrypted messages are not allowed.
11:02:34 AM - Attempting to start a private conversation. Your message will be retransmitted when the private conversation starts.

> In fact, on second thought, if the contact does not support encrypted communication in the first place, why do we attempt to start a private communication?

We don't know until we've exchanged a few messages with them (either the query msg or plaintext with whitespace tags). I've added #25 to provide better notification if the encrypted channel will never be setup.
