### ISSUE TITLE
Manual fingerprint verification UI

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#28]
The UI for manual fingerprint verification looks like:

![2015-02-27-234935_444x95_scrot](https://cloud.githubusercontent.com/assets/368098/6418448/31c09f20-bedb-11e4-97a3-d8aa1fbce6d0.png)

Perhaps we can redesign this?

"I have verified that this is in fact the correct fingerprint" [Dropdown]

The dropdown options will be "Yes" and "No". Somehow I feel that this is more natural that saying "I have" and "I have not" and the options being in the front of the text.

(Feel free to ignore this.)

**Comment by arlolra** [comment]
I see what you're saying. It's probably easier to translate as well.

The current design was pilfered from pidgin-otr. There may have been a specific reason they did it that way but it isn't obvious what that would be.
