### ISSUE TITLE
Differentiate between "private" and "private and verified" conversation

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#29]
Are we differentiating between *private* and *private and verified* conversations? Once a user has verified a contact, can we indicate that in the UI without the user having to click the padlock icon to check it?

**Comment by arlolra** [comment]
We do? The padlock is solid green when it's been verified and an outline of orange we it hasn't. Also, the system notification will clearly says ", but not verfied, " in any messaging.

**Comment by azadi** [comment]
Ah yes, sorry I missed the padlock.

**Comment by arlolra** [comment]
Hmm, that makes me think it isn't apparent enough :(

Any ideas on how to improve it?

**Comment by clokep** [comment]
FWIW Just changing the color isn't very accessible, probably best if the icon changed somehow too...

**Comment by arlolra** [comment]
It changes from an orange outline to solid green. There's also a system message that occurs during that transition.

But yes, this sounds like it may need some improving.

**Comment by azadi** [comment]
I second changing the icon but I am not sure what we can use to show to a verified contact on top of a padlock. Something like a user icon with a green check mark?

**Comment by arlolra** [comment]
Here are the three we have so far, so we know what we're talking about:

![not private](https://raw.githubusercontent.com/arlolra/ctypes-otr/master/chrome/skin/icons/not-private.png) ![unverified](https://raw.githubusercontent.com/arlolra/ctypes-otr/master/chrome/skin/icons/unverified.png) ![private](https://raw.githubusercontent.com/arlolra/ctypes-otr/master/chrome/skin/icons/private.png)

**Comment by azadi** [comment]
Perhaps we can use this:

Open padlock (red): Not private (therefore, not verified)
Green padlock: Private but unverified
Green padlock with a tick?: Private and verified

I think we should also match them up with appropriate tooltips. #34.

**Comment by arlolra** [comment]
https://lists.cypherpunks.ca/pipermail/otr-dev/2015-May/002343.html

**Comment by arlolra** [comment]
https://github.com/redsolution/xabber-android/commit/1ed13b2625d444112d85b3170c78903a11851fae
