### ISSUE TITLE
Use notification bar to verify contacts

### ISSUE THREAD

**Issue by clokep** [arlolra/ctypes-otr#30]
Instead of a modal dialogue, let's interrupt the user less by using a notification bar.

**Comment by azadi** [comment]
My only concern is that a modal dialogue is an "in your face" thing -- which is actually good for this case -- as compared with a notification bar that a user may skip/ignore/not notice.

**Comment by fqueze** [comment]
"a modal dialogue is an "in your face" thing -- which is actually good for this case"
The effect of a modal dialog is that the user's train of thought is interrupted. The user will react by clicking whatever button asap to continue what he was doing, and will often not even read the message.
Whereas on a notification bar the message is very likely to be read before the bar is dismissed.

**Comment by c633** [comment]
can we close this issue?

**Comment by clokep** [comment]
Yes. The verification workflow probably needs some improvements but this initial issue is fixed.
