### ISSUE TITLE
Always encrypted after trying to talk to someone who doesn't have OTR

### ISSUE THREAD

**Issue by clokep** [arlolra/ctypes-otr#31]
I tried to have a conversation w/ someone who doesn't have OTR. I clicked the "Start private conversation", the other user received the text about not supporting OTR...but I kept sending them private stuff until I closed the conversation...and maybe even after that.

**Comment by aleth** [comment]
See also issue #33 for what this looks like from the other end.

**Comment by arlolra** [comment]
After studying the transcript of the conversation, it seems that you two were pasting the whitespace tags and query message to each other. In which case, your client kept trying to initiate a session. The lesson: don't do that :)
