### ISSUE TITLE
Incoming OTR chat request starts with gibberish

### ISSUE THREAD

**Issue by aleth** [arlolra/ctypes-otr#32]
Without OTR installed, I see
"?OTRv23?
clokep@irc.mozilla.org has requested an Off-the Record private conversation. However, you do not have a plugin to support that. See http://otr.cypherpunks.ca/ for more information."

This is good, apart from the ?OTRv23? which is just going to be confusing to people who don't know what it means. Can't OTR inform the client of the precise OTR version *after* discovering OTR is present on both sides?

**Comment by arlolra** [comment]
The gibberish you're referring to is called the query message and it's part of the protocol handshake. That is *how* it discovers OTR is present on the other side. Remember, OTR is layered on top of these transport protocols so there's going to be some user visible characters if the other side does support the protocol.

However, there's a less confusing option. It's called whitespace tags. If you don't explicitly try to start a private conversation, but instead just send the first message in plaintext, OTR will attach those tags to the message and if the other side recognizes them, it'll transparently start the OTR session.

**Comment by aleth** [comment]
I guess I'm confused that part of the query message is meant to be read by a machine, and part of it is meant to be user-visible.

**Comment by arlolra** [comment]
You need to think about how this is all layered on top of the transport. Whitespace tags are ideal but there's nothing to do when someone explicitly asks to go private. It's part of the protocol.
