### ISSUE TITLE
Recognize when the other side doesn't support OTR

### ISSUE THREAD

**Issue by aleth** [arlolra/ctypes-otr#33]
After sending "...has requested an Off-the Record private conversation. However, you do not have a plugin to support that. See http://otr.cypherpunks.ca/ for more information.", *every* message sent appears on the other end as 
1) a long messy message containing "?OTR:AAMCHjjM..."
2) a second message containing plaintext + random whitespace.
Obviously, this is really annoying if you're talking to someone who can't turn on OTR.

So the plugin should notice (maybe after a timeout, or after the next incoming message) that the other side doesn't support OTR, let the user know, and fall back to unencrypted chats or whatever is the chosen default. But not keep spamming the other side with 1+2.

**Comment by arlolra** [comment]
The info here is helpful but covered by #31, #32 and #25.
