### ISSUE TITLE
Private, but unverified, conversation with $USER started.

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#35]
> Private, but unverified, conversation with $USER started.

I think the distinction is that the conversation is encrypted but the **contact** is unverified. In this context, I am not sure what a user will think of with an "unverified" conversation. Can we reword this?

> Private conversation with unverified $USER started.

Perhaps? Sorry for nitpicking. I know this can't be explained in one line but I discussed this with another user and she was also of the opinion that since we are saying authenticate contact in the notification bar, it's better to say that the user is unverified rather than the conversation.

**Comment by arlolra** [comment]
Hmm, looks like you made this point in #17 but I fixed it in the wrong way :(

**Comment by azadi** [comment]
Yeah, I think it should be either of these (suggestions welcome):

> Private conversation with unverified contact $USER started.

or,

> Private conversation with unauthenticated contact $USER started.

Or even,

> Private conversation with $USER started. Please authenticate this contact.

**Comment by arlolra** [comment]
I changed it to "The current conversation is private, but %S's identity has not been verified."
