### ISSUE TITLE
Contact verification message for users

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#36]
Two users, *X* and *Y*. With *X*, I initiate an authentication request using shared secret.

The message in *X*'s window after a successful authentication is:

> You have verified X's identity.

The message in *Y*'s window is:

> You have verified Y's identity.

But, *X* has verified the identity of *Y*, and *Y* still has not verified *X*. The messages should be:

(In *X*):

> You have verified Y's identity.

(In *Y*):

> *X* has verified your identity. You should do the same with her.

(Sorry if this is not clear.)

**Comment by arlolra** [comment]
No, that's not how it works. If you're using a shared secret, then both parties are verifying each other. It's only the question / answer that works as you've described here. Think about it and test in pidgin-otr if you don't believe me.

**Comment by azadi** [comment]
OK sure, but then shouldn't the message in *X*'s window be that X has verified Y? Because right now it says that X has verified X.

**Comment by arlolra** [comment]
Ah, does it? I got caught up with "You should do the same with her." part and failed to read this properly. Let me verify that.

**Comment by arlolra** [comment]
I failed to reproduce that. Can you confirm?

**Comment by azadi** [comment]
It's quite possible that the intended operation is what is described by the OTR protocol, but this is what happens:

I have two contacts, X and Y. I start authentication from X using shared secret and the authentication is successful.

In X, the message I see is:

> You have verified X's identity.

And in Y:

> You have verified Y's identity.

What I am thinking is, shouldn't it say that X has verified Y and that Y has verified X? This will make it more clear to X user that Y has verified her, and to Y that X has verified her. Right now, we are saying to X that "You have verified X's identity", while it is in fact both X and Y that have verified each other.

**Comment by arlolra** [comment]
There are two separate issues here:

* You're opening two accounts on one client and then authenticating each other, which is confusing you a little. What you're failing to realize is that the window that says X, is actually account Y. The window title displays who you're talking to, not who you are. In which case, the strings are correct.

* The second part needs some thought, but you're probably right that the message for the shared secret can be improved to "Your mutual identities have been verified", or some such.

**Comment by azadi** [comment]
re: 1: Aah yes, I was confusing them since I had two windows open side-by-side. Sorry for the noise.
