### ISSUE TITLE
Use either authenticated contact or verified contact

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#37]
In some places, we say *authenticate* contact, and in other places we say *verify* contact.

For example, the notification bar says:

> User has not been authenticated yet. You should authenticate this contact.

And then there is a button below it that says *Verify*.

While the message says "*Private, but unverified, conversation with user started.*" (See #17. Suggested message also says "verified").

We should use one of these words -- either *authenticate* or *verify* -- consistently, so as to not confuse the user.

**Comment by arlolra** [comment]
Good point.

**Comment by arlolra** [comment]
Which do you prefer? I'm leaning towards "authenticate".

**Comment by arlolra** [comment]
Actually, for the most part, we've gone with variations of "their identity has not been verified." I'll stick to that.
