### ISSUE TITLE
Verify button in notification bar

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#38]
![2015-03-02-115703_234x49_scrot](https://cloud.githubusercontent.com/assets/368098/6436294/3779460c-c0d3-11e4-91f9-f6a49474ea3f.png)

What is the "U" in the verify button? Is it the access key for the button? If yes, it doesn't seem to work and  also, we should change it to "V" perhaps?

**Comment by arlolra** [comment]
Hmm, I suppose it's the access key. It isn't present on OS X.
