### ISSUE TITLE
Verify contact notification bar frequency

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#39]
*X* starts a conversation with *Y* for the first time and sees the notification bar to authenticate *Y*. *X* ignores it, carries on the conversation and closes the window.

*X* then again starts the conversation with *Y*. This time though, there is no notification bar that nudges *X* to verify *Y*. 

Is that intentional and we only show the bar the first time *X* will talk with *Y*?

**Comment by arlolra** [comment]
It was intentional on my part. The nudge only occurs the first time you see a new fingerprint.

Do you want to change it?

**Comment by azadi** [comment]
Since verification is an important part of the process, I think we should nudge the user until they have authenticated a particular contact (fingerprint). Since private conversations are a default policy, I think contact authentication should also follow that.

(This should not be high on the priority list though.)

**Comment by arlolra** [comment]
In e91fe5e, I made this configurable. The default will be to always nudge for unverified conversation. But that can be toggled to only nudge the first time you see a new fingerprint.
