### ISSUE TITLE
Empty string for shared secret/answer is acceptable

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#40]
Leaving the text box blank for shared secret/answer works and the authentication is successful. This should probably be not allowed.

**Comment by azadi** [comment]
I tested this again and another related issue will be the notification to the user that an empty answer/secret is not acceptable. Since we are avoiding modal dialogues, should we say this using a notification bar or ...?

**Comment by arlolra** [comment]
See 638c48b8b87dbc980e7d06c4564811a1701de1e3.

**Comment by azadi** [comment]
That's ... weird. So I am guessing the protocol says nothing about this?

**Comment by arlolra** [comment]
SMP is verifying two strings are the same without revealing any knowledge about them. It shouldn't matter for the security of the protocol.

However, usability is another issue altogether. We should be encouraging safer behaviour.
