### ISSUE TITLE
Message not sent when reopening a conversation

### ISSUE THREAD

**Issue by aleth** [arlolra/ctypes-otr#51]
With a contact whose fingerprint has been stored in a previous session for both recipient X and sender, one gets "X has already closed their private connection to you. Your message was not sent. Either end your private conversation, or restart it." if X has closed the conversation.

Naively, expected behaviour would be to renegotiate the private state and then send the message?

Similarly, when opening a new conversation with X, there is a "not private" system message. Should it be assumed that as we have the fingerprint, the conversation will be private unless we find out otherwise (if opportunistic encryption is turned on)?

**Comment by arlolra** [comment]
With opportunistic encryption, the first message that you send is in plaintext with whitespace tags appended to the end. If the receiving client has OTR enabled, it'll detect those tags and then negotiate a secure session.

So, with that in mind, it's important that, when you end the conversation (here closing the conversation sends the disconnect message #1 ... this is why we added the holdByDefault pref in https://github.com/mozilla/releases-comm-central/commit/e39518976f3b882993204c465a2a6ff92d0c98a0), the contact has to made explicitly aware that we're switching back to sending in plaintext. Requiring the user action here is for their benefit.

Does that help?

**Comment by aleth** [comment]
Thanks! From the point of view of the sender, a private conversation is clearly desired at that point (because the conversation was only closed at the other end). Would it make sense, instead of the system message that the message wasn't sent, to automatically try to restart the private conversation and then send the message? (And putting up a system message if that fails.) Or does that make assumptions that may be invalid?

**Comment by arlolra** [comment]
It assumes we have a reliable way of determining if the other side still supports OTR (that's #25), which at present we don't. If the other side doesn't, the query message we sent will just hang in the air. We can always set a timer to bail after a reasonable amount of time and display the system message.

One reason why your contact may have ended the conversation (getting us into this state) is that they were changing devices, and now they're no longer somewhere with OTR.

I agree that this experience can be improved though.

**Comment by arlolra** [comment]
I've updated #25 with the idea here.
