### ISSUE TITLE
Useless blank lines if receiver is not using OTR

### ISSUE THREAD

**Issue by clokep** [arlolra/ctypes-otr#54]
From @PrezNattyGibbs
> When I talk to you on Instantbird, your first few messages usually come 
through with an extra space under them.  Not sure why or if this is a 
big deal.

![instantbird](https://cloud.githubusercontent.com/assets/517124/8415120/a6c4a0c0-1e6a-11e5-996f-b7ed441945da.png)

Maybe we should `trim()` things before display?

**Comment by arlolra** [comment]
No, these are the whitespace tags that OTR appends.
https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/libotr.js#L353

You see that they stop as soon as you get a message back from your contact in plaintext after sending them. After one roundtrip, OTR knows to stop using them.

We can turn them off by removing
https://github.com/arlolra/ctypes-otr/blob/master/chrome/content/libotr.js#L358
but then your encryption isn't so opportunistic.

**Comment by clokep** [comment]
@arlolra I think you missed what I'm suggesting. The user on the *other* side of the connection is what I'm concerned about. That's a screenshot from someone *NOT* using OTR.

**Comment by arlolra** [comment]
@clokep Yup, totally missed that :)

Good idea. I'll submit a patch.

**Comment by arlolra** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1178550

**Comment by arlolra** [comment]
r+'d upstream
