### ISSUE TITLE
Keep notification bar to verify open until user dismisses or success

### ISSUE THREAD

**Issue by arlolra** [arlolra/ctypes-otr#56]
> Once a new OTR session is established, there is this nice obvious black line
  at the top asking you to verify which I think is awesome. However, if auth
  fails, this line disappears and it's not very obvious to use the "lock" at
  the top to get a button to verify.

> I would suggest to keep that annoying black line as long as the contact has
  not been verified (even on failure) except if the "X" to close it has been
  pressed.

/cc @dgoulet

**Comment by tnull** [comment]
Am I correct that this is a duplicate of #62? Then my PR #68 should fix this also.

**Comment by arlolra** [comment]
Yup, looks like it. Good catch!

**Comment by arlolra** [comment]
Fixed in #68
