### ISSUE TITLE
Nudge for verification even if cancelled by user

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#62]
To reproduce: start a conversation with a contact. You will be asked to verify. Pick any method but instead of actually going ahead with it, cancel it. At this point, the notification bar for verification is no longer present. Are we doing that on purpose?

How it should be (IMO): Even if a user starts and cancels the verification process, we still show the notification bar.

**Comment by arlolra** [comment]
Fixed in #68
