### ISSUE TITLE
Crash on connecting to a XMPP account and adding contact

### ISSUE THREAD

**Issue by azadi** [arlolra/ctypes-otr#85]
On connecting to an XMPP account, the contact window disappears and I am asked to enter the fingerprint for my contacts. Clicking skip once works at times but almost always crashes on the second time. 

#76 talks about not asking for fingerprints to be added for existing contacts. This makes sense. We should only prompt for fingerprints when a new contact is added and not every time the account is connected. But as of now I am getting this error even when trying to add a new contact.

I get this error:

```
Timestamp: 17/08/16 07:47:45 PM
Warning: Unhandled IQ result stanza.
Source File: resource:///modules/xmpp.jsm
Line: 1607
Source Code:
prpl-jabber: XMPPAccountPrototype.onIQStanza
```

Surprisingly, I also get this error when removing a contact. Let me know if you need me to check anything else.

@c633

**Comment by azadi** [comment]
If one other person can reproduce this bug then I think this will block our next release.

**Comment by arlolra** [comment]
Did you try disabling the OTR extension and confirming that adding a contact works on your build w/o it?

**Comment by azadi** [comment]
Just tried disabling the OTR extension and adding a contact: I still get the error I pasted above, but no crash. So the unhandled stanza is not from the OTR extension but maybe it is crashing it?

**Comment by arlolra** [comment]
The stanza is probably unrelated.  When you say crash, does the program exit?  Or just the window disappears?

We can probably just disable launching the fingerprint addition window on adding a contact altogether, and just leave it for manual addition for the time being, if this and #76 prove hard to fix.  But I haven't looked at either in much detail yet.

**Comment by azadi** [comment]
The contact window disappears and the program also crashes, though I have not been able to pinpoint the exact cause of the crash.

I am fine with disabling this for now and releasing.

**Comment by c633** [comment]
I just tried reproducing this bug. 
> When you say crash, does the program exit? Or just the window disappears?
>> The contact window disappears and the program also crashes.

On my machine (macOS), the contact window disappears, and if I open the error console, it disappears too (one by one, after the 3rd `Skip` click). However, the program doesn't exit. 

> I am fine with disabling this for now and releasing.

I agree.

**Comment by arlolra** [comment]
> > We can probably just disable launching the fingerprint addition window on adding a contact altogether, and just leave it for manual addition for the time being.

> I agree.

Ok, I did that in f5cc35a72065d56df9e1fac47cf9a247aebc787b so we can get a release out the door.  We can always revisit it later.
