### ISSUE TITLE
Error in prefs (in tor message)

### ISSUE THREAD

**Issue by beliashou** [arlolra/ctypes-otr#91]
Thank you for your product. 

When I go to prefs of ctypes-otr in my tor messenger, I see:

```
XML Parsing Error: undefined entity
Location: chrome://otr/content/prefs.xul
Line Number 6, Column 1:<prefwindow id="otr-prefwindow"
^
```

When I start my chat, I see messages and buttons not russian or english, but like this: "المحادثة الحالية ليست خاصة."

Linux xubuntu 16.04, Tor messenger 0.2.0b2 (beta)

**Comment by c633** [comment]
This is due to some missing translations of non-english languages.
Here are steps to change the language to English:

1. Open `Preferences` > `Advanced` > `Config Editor ...`
2. Press the big button labeled "I'll be careful, I promise!".
3. In the search box, paste `general.useragent.locale`
4. In the search results, double-click `general.useragent.locale` and set its value to `en-US`
5. Restart Tor Messenger for the change to take effect.

Hope this help.

**Comment by beliashou** [comment]
@c633 , thank you for answer, but "general.useragent.locale" have already been set to "en-US".

**Comment by c633** [comment]
@beliashou What is your OS's language? If it is not `en`, in the step 3 and 4 above, search for `intl.locale.matchOS` and change its value to `false`.

**Comment by beliashou** [comment]
Wow! Thank you! It solve the problem!

**Comment by arlolra** [comment]
@c633 @azadi We should patch this in Tor Messenger until [trac 10945](https://trac.torproject.org/projects/tor/ticket/10945) is complete. Either,

* set `intl.locale.matchOS` to `false` for all in the [prefs patch](https://github.com/TheTorProject/tor-messenger-build/blob/master/projects/instantbird/preferences.patch)
* or, remove the incomplete translations from this extension for the time being.

**Comment by c633** [comment]
I'd rather go with the later. Maybe we have a `localization` branch with current translations and remove the incomplete translations from `master` branch.

**Comment by arlolra** [comment]
Another option is,

* Import the translations before each release.  Apparently these are being localized in transifex, https://www.transifex.com/otf/torproject/content/

**Comment by arlolra** [comment]
> I'd rather go with the later.

Ok, let's do that.  We should,

- [ ] Remove the current outdated non-en translations (maybe to another branch)
- [ ] Write an import from transifex script (can borrow from [TorBirdy](https://github.com/ioerror/torbirdy/blob/master/import-translations.sh))
- [ ] Update the [release process](https://github.com/arlolra/ctypes-otr#release) to include running the script

> P.S: Sorry because of hastily closing this issue :(

Not a problem.  Thanks for quickly identifying the issue and helping the user.

**Comment by azadi** [comment]
For now (which means for the upcoming release), I am fine with setting the pref to false unless you strongly disagree :)

**Comment by arlolra** [comment]
> I am fine with setting the pref to false unless you strongly disagree

I think @c633 is saying the user experience is better when the translation is done in best effort.

**Comment by arlolra** [comment]
This was also reported on trac, https://trac.torproject.org/projects/tor/ticket/20231

Just noting the cross reference.
